loomx.loom_version="1.17-SNAPSHOT"

mod.id = "vcc"
mod.name = "Vesper's Compatibility Compendium"
mod.group = "dev.vesper"
mod.version = "0.4.0"
mod.channel_tag = ""
mod.description = "Various mod integrations, fixes and tweaks"
mod.authors = ["VesMaybeVesper"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/vesmaybevesper/Vespers-Compatibility-Compendium"
mod.homepage_url = "https://github.com/vesmaybevesper/Vespers-Compatibility-Compendium"
mod.issues_url = "https://github.com/vesmaybevesper/Vespers-Compatibility-Compendium/issues"
mod.discord_url = "https://fluxer.gg/QzoBSTAo"
mod.environment = "both"
[[mod.pom.developers]]
id = "vesmaybevesper"
name = "VesMaybeVesper"

[fabric]
deps.fabric-loader = "0.19.3"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.11+1.20.1"
deps.modmenu = "7.2.2"
deps.yet_another_config_lib_v3= "3.6.6+1.20.1-fabric"
deps.eveningstarlib= "1.2.1-fabric+1.20.1"
deps.effective= "2.3.2-1.20.1"
deps.lodestone= "1.20.1-1.6.2.3f"
deps.wakes= "0.4.0+1.20.1"
deps.effectual= "4EuXjiZd"
deps.cloth-config= "2xQdCMyG"
deps.architectury-api= "9.2.14+fabric"
deps.particle-rain= "v4-beta.11+1.20.1-fabric"
deps.entity_texture_features= "v0btz5GE"
deps.iceberg= "AiO84cp2"
deps.jade= "ahavHbAT"
deps.jei= "wrBdplEy"
deps.supplementaries= "i7ejA878"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.15+1.21.1"
deps.modmenu = "11.0.4"
deps.yet_another_config_lib_v3= "3.8.2+1.21.1-fabric"
deps.eveningstarlib= "1.2.1-fabric+1.21.1"
deps.effective= "2.4.8-1.21.1"
deps.lodestone= "1.21.1-1.7.0.5-fabric"
deps.wakes= "0.4.1+1.21.1"
deps.effectual= "P9ZLB72Q"
deps.cloth-config= "HpMb5wGb"
deps.architectury-api= "13.0.11+fabric"
deps.particle-rain= "v4-beta.11+1.21.1-fabric"
deps.entity_texture_features= "udcdeUXw"
deps.iceberg= "7ITFAyW8"
deps.jade= "adpNvTZS"
deps.jei= "KTbbPlfR"
deps.supplementaries= "svQdnO8W"

[fabric."1.21.11"]
deps.minecraft = "1.21.11"
deps.fabric-api = "0.141.6+1.21.11"
deps.modmenu = "17.0.1-beta.1"
deps.yet_another_config_lib_v3= "3.8.2+1.21.11-fabric"
deps.eveningstarlib= "1.2.1-fabric+1.21.11"
deps.wakes= "0.5.1+1.21.11"
deps.effectual= "PP1YHzMW"
deps.cloth-config= "xuX40TN5"
deps.architectury-api= "19.0.1+fabric"
deps.particle-rain= "v4-beta.11+1.21.11-fabric"
deps.entity_texture_features= "rAQimlSn"
deps.iceberg= "yRNBxEJF"
deps.jei= "QWzRajBo"

[fabric."26.2"]
deps.minecraft = "26.2"
deps.fabric-api = "0.157.0+26.2"
deps.modmenu = "20.0.1"
deps.yet_another_config_lib_v3= "3.9.6+26.2-fabric"
deps.eveningstarlib= "1.2.1-fabric+26.2"
deps.wakes= "0.7.1+26.2"
deps.effectual= "s7hy9CGX"
deps.cloth-config= "Nv3xnWXd"
deps.architectury-api= "21.0.7+fabric"
deps.particle-rain= "v4-beta.11+26.2-fabric"
deps.entity_texture_features= "HLCBKYFD"
deps.iceberg= "V5RnWL87"
deps.jei= "AFgObZjc"

[forge]

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.4.10"
deps.yet_another_config_lib_v3= "3.6.6+1.20.1-forge"
deps.eveningstarlib= "1.2.1-forge+1.20.1"
deps.wakes= "0.4.0+1.20.1"
deps.effectual= "4EuXjiZd"
deps.cloth-config= "2xQdCMyG"
deps.architectury-api= "9.2.14+forge"
deps.particle-rain= "v4-beta.11+1.20.1-forge"
deps.entity_texture_features= "v0btz5GE"
deps.iceberg= "AiO84cp2"
deps.jade= "ahavHbAT"
deps.jei= "wrBdplEy"
deps.supplementaries= "i7ejA878"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"

[neoforge."1.21.11"]
deps.minecraft = "1.21.711"
deps.neoforge = "21.11.0-beta"

[neoforge."26.2"]
deps.minecraft = "26.2"
deps.neoforge = "26.2.0.0-beta"
